### ISSUE TITLE
Anyway to force certain js types for different mysql types ?

### ISSUE THREAD

**Issue by OultimoCoder** [depot/kysely-planetscale#29]
I would like e.g. for decimal types to have the type returned from planetscale as a string to maintain precision. I'm not too sure how to do this. I saw in the Kysely docs you could do a conversion via cast but at that point it is too late no?

Any way to maintain precision?  Or do I have to perform a cast when retrieving it?

**Comment by jacobwgillespie** [comment]
Hey! So it's possible to cast values returned from the database to JS types explicitly, via a custom cast function (https://github.com/depot/kysely-planetscale#custom-cast-function), but otherwise this adapter just returns the types directly from https://github.com/planetscale/database-js. You may want to open an issue over there if you're seeing return types that you don't expect.
